endpoints.health.enabled: true

hazelcast.max.no.heartbeat.seconds: 6

admin-application.url: http://admin-application:8080/admin/companies

news-application.url: http://news-application:8080/news/twitter
